// Copyright (C) 2026 SayIt Contributors
//
// This file is part of SayIt.
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

class VoiceInfo {
  final String name;
  final String value;
  final String languageCode;
  final String languageName;
  final String gender;

  const VoiceInfo({
    required this.name,
    required this.value,
    required this.languageCode,
    required this.languageName,
    required this.gender,
  });
}

const voiceData = <VoiceInfo>[
  VoiceInfo(name: '晓晓(女)-温柔亲切', value: 'zh-CN-XiaoxiaoNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '小艺(女)-青春活泼', value: 'zh-CN-XiaoyiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '云健(男)-健康活力', value: 'zh-CN-YunjianNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云希(男)-自然流畅', value: 'zh-CN-YunxiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云夏(男)-自然流畅', value: 'zh-CN-YunxiaNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云扬(男)-成熟专业', value: 'zh-CN-YunyangNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云野(男)-沉稳有力', value: 'zh-CN-YunyeNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '晓涵(女)-知性冷静', value: 'zh-CN-XiaohanNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '晓睿(女)-聪慧成熟', value: 'zh-CN-XiaoruiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '晓双(女)-俏皮活泼', value: 'zh-CN-XiaoshuangNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '晓瑄(女)-温婉优雅', value: 'zh-CN-XiaoxuanNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '晓燕(女)-亲和温暖', value: 'zh-CN-XiaoyanNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '小雪(女)-轻柔甜美', value: 'zh-CN-XiaoxueNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '云绯(女)-优雅知性', value: 'zh-CN-YunfeiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '云霖(男)-沉稳温和', value: 'zh-CN-YunlinNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云龙(男)-浑厚有力', value: 'zh-CN-YunlongNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '小北(女)-东北风味', value: 'zh-CN-XiaobeiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '小妮(女)-陕西方言', value: 'zh-CN-XiaoniNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '晓瑾(女)-甜美清新', value: 'zh-CN-HsiaoChromeNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '小白(女)-自然流畅', value: 'zh-CN-XiaobaiNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '小梦(女)-自然流畅', value: 'zh-CN-XiaomengNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '云佳(女)-自然流畅', value: 'zh-CN-YunjiaNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'female'),
  VoiceInfo(name: '云皓(男)-自然流畅', value: 'zh-CN-YunhaoNeural', languageCode: 'zh-CN', languageName: '中文(简体)', gender: 'male'),
  VoiceInfo(name: '云希(男)-活泼可爱', value: 'zh-CN-YunxiNeural', languageCode: 'zh-TW', languageName: '中文(台语)', gender: 'male'),
  VoiceInfo(name: '晓汝(女)-自然流畅', value: 'zh-TW-HsiaoYuNeural', languageCode: 'zh-TW', languageName: '中文(台语)', gender: 'female'),
  VoiceInfo(name: '云泽(男)-成熟台式', value: 'zh-TW-YunjheNeural', languageCode: 'zh-TW', languageName: '中文(台语)', gender: 'male'),
  VoiceInfo(name: '晓晨(女)-自然流畅', value: 'zh-TW-HsiaoChenNeural', languageCode: 'zh-TW', languageName: '中文(台语)', gender: 'female'),
  VoiceInfo(name: '晓洁(男)-自然流畅', value: 'zh-TW-HsiaoChiehNeural', languageCode: 'zh-TW', languageName: '中文(台语)', gender: 'male'),
  VoiceInfo(name: '晓艾(女)-自然流畅', value: 'zh-HK-AriaNeural', languageCode: 'zh-HK', languageName: '中文(粤语)', gender: 'female'),
  VoiceInfo(name: '萧喀(女)-港式粤语', value: 'zh-HK-HiuGaaiNeural', languageCode: 'zh-HK', languageName: '中文(粤语)', gender: 'female'),
  VoiceInfo(name: '萧曼(女)-温柔粤语', value: 'zh-HK-HiuMaanNeural', languageCode: 'zh-HK', languageName: '中文(粤语)', gender: 'female'),
  VoiceInfo(name: '云龙(男)-港式男声', value: 'zh-HK-WanLungNeural', languageCode: 'zh-HK', languageName: '中文(粤语)', gender: 'male'),
  VoiceInfo(name: '艾姆(女)-自然流畅', value: 'en-US-AnaNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'female'),
  VoiceInfo(name: '安弟(男)-成熟稳重', value: 'en-US-AndrewNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '艾维亚(女)-甜美亲切', value: 'en-US-AvaNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'female'),
  VoiceInfo(name: '布林(男)-自然对话', value: 'en-US-BrianNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '克里斯(男)-专业播音', value: 'en-US-ChristopherNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '艾玛(女)-优雅知性', value: 'en-US-EmmaNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'female'),
  VoiceInfo(name: '埃里克(男)-清晰有力', value: 'en-US-EricNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '盖伊(男)-中性自然', value: 'en-US-GuyNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '珍妮(女)-甜美柔和', value: 'en-US-JennyNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'female'),
  VoiceInfo(name: '米歇尔(女)-自然流畅', value: 'en-US-MichelleNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'female'),
  VoiceInfo(name: '罗杰(男)-温和男声', value: 'en-US-RogerNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '斯蒂芬(男)-威尔士特色', value: 'en-US-SteffanNeural', languageCode: 'en-US', languageName: '英语(美)', gender: 'male'),
  VoiceInfo(name: '艾米(女)-自然流畅', value: 'en-GB-AmyNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'female'),
  VoiceInfo(name: '艾玛(女)-自然流畅', value: 'en-GB-EmmaNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'female'),
  VoiceInfo(name: '梅根(女)-自然流畅', value: 'en-GB-MeganNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'female'),
  VoiceInfo(name: '瑞安(男)-英式沉稳', value: 'en-GB-RyanNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'male'),
  VoiceInfo(name: '索尼娅(女)-英式优雅', value: 'en-GB-SoniaNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'female'),
  VoiceInfo(name: '托马斯(男)-英式传统', value: 'en-GB-ThomasNeural', languageCode: 'en-GB', languageName: '英语(英)', gender: 'male'),
  VoiceInfo(name: '娜塔莎(女)-澳式亲切', value: 'en-AU-NatashaNeural', languageCode: 'en-AU', languageName: '英语(澳)', gender: 'female'),
  VoiceInfo(name: '威廉(男)-自然流畅', value: 'en-AU-WilliamNeural', languageCode: 'en-AU', languageName: '英语(澳)', gender: 'male'),
  VoiceInfo(name: '克拉拉(女)-加式清晰', value: 'en-CA-ClaraNeural', languageCode: 'en-CA', languageName: '英语(加)', gender: 'female'),
  VoiceInfo(name: '利亚姆(男)-加式清晰', value: 'en-CA-LiamNeural', languageCode: 'en-CA', languageName: '英语(加)', gender: 'male'),
  VoiceInfo(name: '尼尔贾(女)-印度特色', value: 'en-IN-NeerjaNeural', languageCode: 'en-IN', languageName: '英语(印)', gender: 'female'),
  VoiceInfo(name: '普拉巴特(男)-印度男声', value: 'en-IN-PrabhatNeural', languageCode: 'en-IN', languageName: '英语(印)', gender: 'male'),
  VoiceInfo(name: '艾米丽(女)-自然流畅', value: 'en-IE-EmilyNeural', languageCode: 'en-IE', languageName: '英语(爱)', gender: 'female'),
  VoiceInfo(name: '康纳(男)-爱尔兰沉稳', value: 'en-IE-ConnorNeural', languageCode: 'en-IE', languageName: '英语(爱)', gender: 'male'),
  VoiceInfo(name: '米itchell(男)-NZ男声', value: 'en-NZ-MitchellNeural', languageCode: 'en-NZ', languageName: '英语(新西)', gender: 'male'),
  VoiceInfo(name: '莫里(女)-活力四射', value: 'en-NZ-MollyNeural', languageCode: 'en-NZ', languageName: '英语(新西)', gender: 'female'),
  VoiceInfo(name: '露娜(女)-自然流畅', value: 'en-SG-LunaNeural', languageCode: 'en-SG', languageName: '英语(新)', gender: 'female'),
  VoiceInfo(name: '韦恩(男)-自然流畅', value: 'en-SG-WayneNeural', languageCode: 'en-SG', languageName: '英语(新)', gender: 'male'),
  VoiceInfo(name: '艾娃(女)-自然流畅', value: 'en-ZA-ZoeNeural', languageCode: 'en-ZA', languageName: '英语(南)', gender: 'female'),
  VoiceInfo(name: '卢克(男)-自然流畅', value: 'en-ZA-LukeNeural', languageCode: 'en-ZA', languageName: '英语(南)', gender: 'male'),
  VoiceInfo(name: '艾琳(女)-自然流畅', value: 'ja-JP-AiNeural', languageCode: 'ja-JP', languageName: '日语', gender: 'female'),
  VoiceInfo(name: '健太(男)-日语男声', value: 'ja-JP-KeitaNeural', languageCode: 'ja-JP', languageName: '日语', gender: 'male'),
  VoiceInfo(name: '七海(女)-温柔女声', value: 'ja-JP-NanamiNeural', languageCode: 'ja-JP', languageName: '日语', gender: 'female'),
  VoiceInfo(name: '诗织(女)-自然流畅', value: 'ja-JP-ShioriNeural', languageCode: 'ja-JP', languageName: '日语', gender: 'female'),
  VoiceInfo(name: '贤俊(男)-韩语男声', value: 'ko-KR-InJoonNeural', languageCode: 'ko-KR', languageName: '韩语', gender: 'male'),
  VoiceInfo(name: '先怡(女)-韩语甜美', value: 'ko-KR-SunHiNeural', languageCode: 'ko-KR', languageName: '韩语', gender: 'female'),
  VoiceInfo(name: '阿莱克西(女)-自然流畅', value: 'fr-FR-AlexisNeural', languageCode: 'fr-FR', languageName: '法语', gender: 'male'),
  VoiceInfo(name: '丹妮丝(女)-法式优雅', value: 'fr-FR-DeniseNeural', languageCode: 'fr-FR', languageName: '法语', gender: 'female'),
  VoiceInfo(name: '埃洛伊塞(女)-法式浪漫', value: 'fr-FR-EloiseNeural', languageCode: 'fr-FR', languageName: '法语', gender: 'female'),
  VoiceInfo(name: '亨利(男)-法式优雅', value: 'fr-FR-HenriNeural', languageCode: 'fr-FR', languageName: '法语', gender: 'male'),
  VoiceInfo(name: '阿丽西亚(女)-自然流畅', value: 'it-IT-AlessiaNeural', languageCode: 'it-IT', languageName: '意大利语', gender: 'female'),
  VoiceInfo(name: '迭戈(男)-西班牙男声', value: 'it-IT-DiegoNeural', languageCode: 'it-IT', languageName: '意大利语', gender: 'male'),
  VoiceInfo(name: '埃尔莎(女)-意大利温柔', value: 'it-IT-ElsaNeural', languageCode: 'it-IT', languageName: '意大利语', gender: 'female'),
  VoiceInfo(name: '伊莎贝拉(女)-意式热情', value: 'it-IT-IsabellaNeural', languageCode: 'it-IT', languageName: '意大利语', gender: 'female'),
  VoiceInfo(name: '阿玛莉亚(女)-自然流畅', value: 'de-DE-AmalaNeural', languageCode: 'de-DE', languageName: '德语', gender: 'female'),
  VoiceInfo(name: '康拉德(男)-自然流畅', value: 'de-DE-ConradNeural', languageCode: 'de-DE', languageName: '德语', gender: 'male'),
  VoiceInfo(name: '卡佳(女)-自然流畅', value: 'de-DE-KatjaNeural', languageCode: 'de-DE', languageName: '德语', gender: 'female'),
  VoiceInfo(name: '基里安(男)-自然流畅', value: 'de-DE-KillianNeural', languageCode: 'de-DE', languageName: '德语', gender: 'male'),
  VoiceInfo(name: '阿尔瓦罗(男)-西语男声', value: 'es-ES-AlvaroNeural', languageCode: 'es-ES', languageName: '西班牙语', gender: 'male'),
  VoiceInfo(name: '埃尔维拉(女)-自然流畅', value: 'es-ES-ElviraNeural', languageCode: 'es-ES', languageName: '西班牙语', gender: 'female'),
  VoiceInfo(name: '达莉亚(女)-自然流畅', value: 'es-MX-DaliaNeural', languageCode: 'es-MX', languageName: '西班牙语(墨)', gender: 'female'),
  VoiceInfo(name: '豪尔赫(男)-自然流畅', value: 'es-MX-JorgeNeural', languageCode: 'es-MX', languageName: '西班牙语(墨)', gender: 'male'),
  VoiceInfo(name: '安东尼奥(男)-自然流畅', value: 'pt-BR-AntonioNeural', languageCode: 'pt-BR', languageName: '葡萄牙语(巴)', gender: 'male'),
  VoiceInfo(name: '布伦达(女)-自然流畅', value: 'pt-BR-BrendaNeural', languageCode: 'pt-BR', languageName: '葡萄牙语(巴)', gender: 'female'),
  VoiceInfo(name: '唐尼(男)-自然流畅', value: 'pt-BR-DonatoNeural', languageCode: 'pt-BR', languageName: '葡萄牙语(巴)', gender: 'male'),
  VoiceInfo(name: '弗朗西丝卡(女)-自然流畅', value: 'pt-BR-FranciscaNeural', languageCode: 'pt-BR', languageName: '葡萄牙语(巴)', gender: 'female'),
  VoiceInfo(name: '杜阿尔特(男)-葡萄牙男声', value: 'pt-PT-DuarteNeural', languageCode: 'pt-PT', languageName: '葡萄牙语(葡)', gender: 'male'),
  VoiceInfo(name: '拉奎尔(女)-自然流畅', value: 'pt-PT-RaquelNeural', languageCode: 'pt-PT', languageName: '葡萄牙语(葡)', gender: 'female'),
  VoiceInfo(name: '达里娅(女)-自然流畅', value: 'ru-RU-DariyaNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'female'),
  VoiceInfo(name: '德米特里(男)-俄式沉稳', value: 'ru-RU-DmitryNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'male'),
  VoiceInfo(name: '叶卡捷琳娜(女)-自然流畅', value: 'ru-RU-EkaterinaNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'female'),
  VoiceInfo(name: '伊琳娜(女)-自然流畅', value: 'ru-RU-IrinaNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'female'),
  VoiceInfo(name: '斯维特拉娜(女)-自然流畅', value: 'ru-RU-SvetlanaNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'female'),
  VoiceInfo(name: '塔季扬娜(女)-自然流畅', value: 'ru-RU-TatyanaNeural', languageCode: 'ru-RU', languageName: '俄语', gender: 'female'),
  VoiceInfo(name: '阿赫梅特(男)-土耳其男声', value: 'tr-TR-AhmetNeural', languageCode: 'tr-TR', languageName: '土耳其语', gender: 'male'),
  VoiceInfo(name: '埃梅尔(女)-自然流畅', value: 'tr-TR-EmelNeural', languageCode: 'tr-TR', languageName: '土耳其语', gender: 'female'),
  VoiceInfo(name: '阿卜杜勒(男)-自然流畅', value: 'ar-SA-AbdullahNeural', languageCode: 'ar-SA', languageName: '阿拉伯语', gender: 'male'),
  VoiceInfo(name: '玛丽卡(女)-自然流畅', value: 'ar-SA-MalikaNeural', languageCode: 'ar-SA', languageName: '阿拉伯语', gender: 'female'),
  VoiceInfo(name: '阿德莉亚(女)-自然流畅', value: 'af-ZA-AdriNeural', languageCode: 'af-ZA', languageName: '南非荷兰语', gender: 'female'),
  VoiceInfo(name: '威廉(男)-自然流畅', value: 'af-ZA-WillemNeural', languageCode: 'af-ZA', languageName: '南非荷兰语', gender: 'male'),
  VoiceInfo(name: '阿姆哈(男)-自然流畅', value: 'am-ET-AmehaNeural', languageCode: 'am-ET', languageName: '阿姆哈拉语', gender: 'male'),
  VoiceInfo(name: '梅克德斯(女)-自然流畅', value: 'am-ET-MekdesNeural', languageCode: 'am-ET', languageName: '阿姆哈拉语', gender: 'female'),
  VoiceInfo(name: '阿格涅什卡(女)-自然流畅', value: 'pl-PL-AgnieszkaNeural', languageCode: 'pl-PL', languageName: '波兰语', gender: 'female'),
  VoiceInfo(name: '马雷克(男)-波兰男声', value: 'pl-PL-MarekNeural', languageCode: 'pl-PL', languageName: '波兰语', gender: 'male'),
  VoiceInfo(name: '佐菲亚(女)-波兰优雅', value: 'pl-PL-ZofiaNeural', languageCode: 'pl-PL', languageName: '波兰语', gender: 'female'),
  VoiceInfo(name: '阿尼(女)-自然流畅', value: 'nl-NL-AnnaNeural', languageCode: 'nl-NL', languageName: '荷兰语', gender: 'female'),
  VoiceInfo(name: '科莱特(女)-知性优雅', value: 'nl-NL-ColetteNeural', languageCode: 'nl-NL', languageName: '荷兰语', gender: 'female'),
  VoiceInfo(name: '马丁(男)-荷兰男声', value: 'nl-NL-MaartenNeural', languageCode: 'nl-NL', languageName: '荷兰语', gender: 'male'),
  VoiceInfo(name: '芬娜(女)-荷兰亲切', value: 'nl-NL-FennaNeural', languageCode: 'nl-NL', languageName: '荷兰语', gender: 'female'),
  VoiceInfo(name: '马蒂亚斯(男)-瑞典男声', value: 'sv-SE-MattiasNeural', languageCode: 'sv-SE', languageName: '瑞典语', gender: 'male'),
  VoiceInfo(name: '索菲(女)-瑞典柔和', value: 'sv-SE-SofieNeural', languageCode: 'sv-SE', languageName: '瑞典语', gender: 'female'),
  VoiceInfo(name: '芬恩(男)-挪威男声', value: 'nb-NO-FinnNeural', languageCode: 'nb-NO', languageName: '挪威语', gender: 'male'),
  VoiceInfo(name: '佩妮莱(女)-自然流畅', value: 'nb-NO-PernilleNeural', languageCode: 'nb-NO', languageName: '挪威语', gender: 'female'),
  VoiceInfo(name: '耶珀(男)-丹麦男声', value: 'da-DK-JeppeNeural', languageCode: 'da-DK', languageName: '丹麦语', gender: 'male'),
  VoiceInfo(name: '克里斯托弗(女)-自然流畅', value: 'da-DK-ChristinaNeural', languageCode: 'da-DK', languageName: '丹麦语', gender: 'female'),
  VoiceInfo(name: '哈里(男)-芬兰男声', value: 'fi-FI-HarriNeural', languageCode: 'fi-FI', languageName: '芬兰语', gender: 'male'),
  VoiceInfo(name: '诺拉(女)-北欧清澈', value: 'fi-FI-NooraNeural', languageCode: 'fi-FI', languageName: '芬兰语', gender: 'female'),
  VoiceInfo(name: '阿舒(女)-自然流畅', value: 'hi-IN-AshwiniNeural', languageCode: 'hi-IN', languageName: '印地语', gender: 'female'),
  VoiceInfo(name: '马图尔(男)-自然流畅', value: 'hi-IN-MadhurNeural', languageCode: 'hi-IN', languageName: '印地语', gender: 'male'),
  VoiceInfo(name: '普拉姆瓦迪(女)-泰语柔和', value: 'th-TH-PremwadeeNeural', languageCode: 'th-TH', languageName: '泰语', gender: 'female'),
  VoiceInfo(name: '尼瓦(男)-自然流畅', value: 'th-TH-NiwatNeural', languageCode: 'th-TH', languageName: '泰语', gender: 'male'),
  VoiceInfo(name: '河梅(女)-自然流畅', value: 'vi-VN-HoaiMyNeural', languageCode: 'vi-VN', languageName: '越南语', gender: 'female'),
  VoiceInfo(name: '南明(男)-越南男声', value: 'vi-VN-NamMinhNeural', languageCode: 'vi-VN', languageName: '越南语', gender: 'male'),
  VoiceInfo(name: '阿卜杜勒(男)-自然流畅', value: 'id-ID-ArdiNeural', languageCode: 'id-ID', languageName: '印尼语', gender: 'male'),
  VoiceInfo(name: '加迪斯(女)-印尼温柔', value: 'id-ID-GadisNeural', languageCode: 'id-ID', languageName: '印尼语', gender: 'female'),
  VoiceInfo(name: '亚斯敏(女)-马来清新', value: 'ms-MY-YasminNeural', languageCode: 'ms-MY', languageName: '马来语', gender: 'female'),
  VoiceInfo(name: '奥斯曼(男)-马来深沉', value: 'ms-MY-OsmanNeural', languageCode: 'ms-MY', languageName: '马来语', gender: 'male'),
];

const languages = <Map<String, String>>[
  {'code': 'zh-CN', 'name': '中文(简体)'},
  {'code': 'zh-TW', 'name': '中文(台语)'},
  {'code': 'zh-HK', 'name': '中文(粤语)'},
  {'code': 'en-US', 'name': '英语(美)'},
  {'code': 'en-GB', 'name': '英语(英)'},
  {'code': 'en-AU', 'name': '英语(澳)'},
  {'code': 'en-CA', 'name': '英语(加)'},
  {'code': 'en-IN', 'name': '英语(印)'},
  {'code': 'en-IE', 'name': '英语(爱)'},
  {'code': 'en-NZ', 'name': '英语(新西)'},
  {'code': 'en-SG', 'name': '英语(新)'},
  {'code': 'en-ZA', 'name': '英语(南)'},
  {'code': 'ja-JP', 'name': '日语'},
  {'code': 'ko-KR', 'name': '韩语'},
  {'code': 'fr-FR', 'name': '法语'},
  {'code': 'de-DE', 'name': '德语'},
  {'code': 'it-IT', 'name': '意大利语'},
  {'code': 'es-ES', 'name': '西班牙语'},
  {'code': 'es-MX', 'name': '西班牙语(墨)'},
  {'code': 'pt-BR', 'name': '葡萄牙语(巴)'},
  {'code': 'pt-PT', 'name': '葡萄牙语(葡)'},
  {'code': 'ru-RU', 'name': '俄语'},
  {'code': 'tr-TR', 'name': '土耳其语'},
  {'code': 'ar-SA', 'name': '阿拉伯语'},
  {'code': 'pl-PL', 'name': '波兰语'},
  {'code': 'nl-NL', 'name': '荷兰语'},
  {'code': 'sv-SE', 'name': '瑞典语'},
  {'code': 'nb-NO', 'name': '挪威语'},
  {'code': 'da-DK', 'name': '丹麦语'},
  {'code': 'fi-FI', 'name': '芬兰语'},
  {'code': 'hi-IN', 'name': '印地语'},
  {'code': 'th-TH', 'name': '泰语'},
  {'code': 'vi-VN', 'name': '越南语'},
  {'code': 'id-ID', 'name': '印尼语'},
  {'code': 'ms-MY', 'name': '马来语'},
  {'code': 'af-ZA', 'name': '南非荷兰语'},
  {'code': 'am-ET', 'name': '阿姆哈拉语'},
];

const genders = <Map<String, String>>[
  {'code': 'female', 'name': '女'},
  {'code': 'male', 'name': '男'},
];
